---
layout: post
title: "面试突击83：什么情况会导致@Transactional事务失效？"
date: "2022-09-14T22:21:37.566Z"
---
面试突击83：什么情况会导致@Transactional事务失效？
=================================

一个程序中不可能没有事务，而 Spring 中，事务的实现方式分为两种：编程式事务和声明式事务，又因为编程式事务实现相对麻烦，而声明式事务实现极其简单，所以在日常项目中，我们都会使用声明式事务 @Transactional 来实现事务。

@Transactional 使用极其简单，只需要在类上或方法上添加 @Transactional 关键字，就可以实现事务的自动开启、提交或回滚了，它的基础用法如下：

    @Transactional 
    @RequestMapping("/add")
    public int add(UserInfo userInfo) {
        int result = userService.add(userInfo);
        return result;
    }
    

#### @Transactional 执行流程

**@Transactional 会在方法执行前，会自动开启事务；在方法成功执行完，会自动提交事务；如果方法在执行期间，出现了异常，那么它会自动回滚事务。**

然而，就是看起来极其简单的 @Transactional，却隐藏着一些“坑”，这些坑就是我们今天要讲的主题：导致 @Transactional 事务失效的常见场景有哪些？

在开始之前，我们先要明确一个定义，什么叫做“失效”？

本文中的“失效”指的是“**失去（它的）功效**”，也就是当 @Transactional 不符合我们预期的结果时，我们就可以说 @Transactional 失效了。

那 @Transactional 失效的场景有哪些呢？接下来我们一一来看。

1.非 public 修饰的方法
----------------

**当 @Transactional 修饰的方法为非 public 时，事务就失效了**，比如以下代码当遇到异常之后，不能自动实现回滚：

    @RequestMapping("/save")
    int save(UserInfo userInfo) {
        // 非空效验
        if (userInfo == null ||
            !StringUtils.hasLength(userInfo.getUsername()) ||
            !StringUtils.hasLength(userInfo.getPassword()))
            return 0;
        // 执行添加操作
        int result = userService.save(userInfo);
        System.out.println("add 受影响的行数：" + result);
        int num = 10 / 0; // 此处设置一个异常
        return result;
    }
    

以上程序的运行结果如下：  
![image.png](https://cdn.nlark.com/yuque/0/2022/png/92791/1659838789200-a6fcbfa0-fd27-4e90-9790-4f45af83f677.png#clientId=u5edd51a3-404d-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=541&id=uf6ba7f96&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1082&originWidth=2055&originalType=binary&ratio=1&rotation=0&showTitle=false&size=321821&status=done&style=none&taskId=u045ddc7f-76cc-4e27-ad4b-943d3692db5&title=&width=1027.5)  
**当程序出现运行时异常时，我们预期的结果是事务应该实现自动回滚，也就是添加用户失败，然而当我们查询数据库时，却发现事务并未执行回滚操作**，数据库的数据如下图所示：  
![image.png](https://cdn.nlark.com/yuque/0/2022/png/92791/1659838855241-6b37e58b-27f1-4121-b4c1-a24413a60019.png#clientId=u5edd51a3-404d-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=202&id=u2fd96b7f&margin=%5Bobject%20Object%5D&name=image.png&originHeight=404&originWidth=2084&originalType=binary&ratio=1&rotation=0&showTitle=false&size=36008&status=done&style=none&taskId=u6e1252fc-fba4-45e8-bfbc-327b80a04a3&title=&width=1042)

2.timeout 超时
------------

**当在 @Transactional 上，设置了一个较小的超时时间时，如果方法本身的执行时间超过了设置的 timeout 超时时间，那么就会导致本来应该正常插入数据的方法执行失败**，示例代码如下：

    @Transactional(timeout = 3) // 超时时间为 3s
    @RequestMapping("/save")
    int save(UserInfo userInfo) throws InterruptedException {
        // 非空效验
        if (userInfo == null ||
            !StringUtils.hasLength(userInfo.getUsername()) ||
            !StringUtils.hasLength(userInfo.getPassword()))
            return 0;
        int result = userService.save(userInfo);
        return result;
    }
    

UserService 的 save 方法实现如下：

    public int save(UserInfo userInfo) throws InterruptedException {
        // 休眠 5s
        TimeUnit.SECONDS.sleep(5);
        int result = userMapper.add(userInfo);
        return result;
    }
    

以上程序的运行结果如下：  
![image.png](https://cdn.nlark.com/yuque/0/2022/png/92791/1659840561743-8f39c13b-8303-4a5a-9e83-d9bb32d9bee3.png#clientId=u5edd51a3-404d-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=413&id=uf287aaca&margin=%5Bobject%20Object%5D&name=image.png&originHeight=826&originWidth=2131&originalType=binary&ratio=1&rotation=0&showTitle=false&size=237785&status=done&style=none&taskId=u3a8119f2-a868-4055-a00b-b3ee4836254&title=&width=1065.5)  
数据库没有正确的插入数据，如下图所示：  
![image.png](https://cdn.nlark.com/yuque/0/2022/png/92791/1659840584761-797ff569-a5bd-4450-9256-a71879159471.png#clientId=u5edd51a3-404d-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=177&id=uad8214fd&margin=%5Bobject%20Object%5D&name=image.png&originHeight=353&originWidth=2080&originalType=binary&ratio=1&rotation=0&showTitle=false&size=29164&status=done&style=none&taskId=u7c89c4e2-802c-4925-99ae-712f831df72&title=&width=1040)

3.代码中有 try/catch
----------------

在前面 @Transactional 的执行流程中，我们提到：当方法中出现了异常之后，事务会自动回滚。然而，如果在程序中加了 try/catch 之后，@Transactional 就不会自动回滚事务了，示例代码如下：

    @Transactional
    @RequestMapping("/save")
    public int save(UserInfo userInfo) throws InterruptedException {
        // 非空效验
        if (userInfo == null ||
            !StringUtils.hasLength(userInfo.getUsername()) ||
            !StringUtils.hasLength(userInfo.getPassword()))
            return 0;
        int result = userService.save(userInfo);
        try {
            int num = 10 / 0; // 此处设置一个异常
        } catch (Exception e) {
        }
        return result;
    }
    

以上程序的运行结果如下：  
![image.png](https://cdn.nlark.com/yuque/0/2022/png/92791/1659841577406-5795a42d-f572-4f57-8d1e-5d8a64937518.png#clientId=u5edd51a3-404d-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=129&id=u54ea27ad&margin=%5Bobject%20Object%5D&name=image.png&originHeight=257&originWidth=1641&originalType=binary&ratio=1&rotation=0&showTitle=false&size=29976&status=done&style=none&taskId=ue4ebb1e9-9944-404f-b774-b4718250bd8&title=&width=820.5)  
此时，查询数据库我们发现，**程序并没有执行回滚操作**，数据库中被成功的添加了一条数据，如下图所示：  
![image.png](https://cdn.nlark.com/yuque/0/2022/png/92791/1659841602475-7d02b319-f15b-436b-8753-fc9cd51a83b8.png#clientId=u5edd51a3-404d-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=209&id=ue2f6d901&margin=%5Bobject%20Object%5D&name=image.png&originHeight=417&originWidth=2093&originalType=binary&ratio=1&rotation=0&showTitle=false&size=36249&status=done&style=none&taskId=ub1fe8fad-bc5a-4677-b16d-abe4eb3ef69&title=&width=1046.5)

4.调用类内部 @Transactional 方法
-------------------------

当调用类内部的 @Transactional 修饰的方法时，事务是不会生效的，示例代码如下：

    @RequestMapping("/save")
    public int saveMappping(UserInfo userInfo) {
        return save(userInfo);
    }
    @Transactional
    public int save(UserInfo userInfo) {
        // 非空效验
        if (userInfo == null ||
            !StringUtils.hasLength(userInfo.getUsername()) ||
            !StringUtils.hasLength(userInfo.getPassword()))
            return 0;
        int result = userService.save(userInfo);
        int num = 10 / 0; // 此处设置一个异常
        return result;
    }
    

以上代码我们在添加方法 save 中添加了 @Transactional 声明式事务，并且添加了异常代码，**我们预期的结果是程序出现异常，事务进行自动回滚**，以上程序的执行结果如下：  
![image.png](https://cdn.nlark.com/yuque/0/2022/png/92791/1659841900987-b429323b-c5f0-417e-aab3-53aa5eb537ab.png#clientId=u5edd51a3-404d-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=457&id=ucba86cce&margin=%5Bobject%20Object%5D&name=image.png&originHeight=914&originWidth=1970&originalType=binary&ratio=1&rotation=0&showTitle=false&size=256062&status=done&style=none&taskId=u55cd2afc-1a04-4624-aed7-368b5668703&title=&width=985)  
然而，当我们查询数据库时发现，程序执行并不符合我们的预期，添加的数据并没有进行自动回滚操作，如下图所示：  
![image.png](https://cdn.nlark.com/yuque/0/2022/png/92791/1659842162697-76e27ab1-9f1d-4e44-bd69-bb4d521105f1.png#clientId=u5edd51a3-404d-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=210&id=uf073dfbc&margin=%5Bobject%20Object%5D&name=image.png&originHeight=419&originWidth=2050&originalType=binary&ratio=1&rotation=0&showTitle=false&size=36665&status=done&style=none&taskId=u91a32ad9-5b92-4399-b90a-06080d9f6c4&title=&width=1025)

5.数据库不支持事务
----------

我们程序中的 @Transactional 只是给调用的数据库发送了：开始事务、提交事务、回滚事务的指令，但是如果数据库本身不支持事务，比如 MySQL 中设置了使用 MyISAM 引擎，那么它本身是不支持事务的，这种情况下，即使在程序中添加了 @Transactional 注解，那么依然不会有事务的行为，这就是巧妇也难为无米之炊吧。

总结
--

当声明式事务 @Transactional 遇到以下场景时，事务会失效：

1.  非 public 修饰的方法；
2.  timeout 设置过小；
3.  代码中使用 try/catch 处理异常；
4.  调用类内部 @Transactional 方法；
5.  数据库不支持事务。

#### 参考 & 鸣谢

www.cnblogs.com/frankyou/p/12691463.html

> 是非审之于己，毁誉听之于人，得失安之于数。
> 
> 公众号：Java面试真题解析
> 
> 面试合集：[https://gitee.com/mydb/interview](https://gitee.com/mydb/interview)

关注下面二维码，订阅更多精彩内容。  
![](https://images.cnblogs.com/cnblogs_com/vipstone/848916/o_211225130402_gognzhonghao.jpg)

![](http://icdn.apigo.cn/gitchat/rabbitmq.png?imageView2/0/w/500/h/400)

![微信打赏](http://icdn.apigo.cn/myinfo/wchat-pay.png "微信打赏")  

关注公众号（加好友）： ![](http://icdn.apigo.cn/gongzhonghao2.png?imageView2/0/w/120/h/120)

  
作者： [王磊的博客](http://vipstone.cnblogs.com/)  
出处： [http://vipstone.cnblogs.com/](http://vipstone.cnblogs.com/)