---
layout: post
title: "分享一个你很可能不知道的Java异常实现的缺陷"
date: "2022-12-07T03:21:57.680Z"
---
分享一个你很可能不知道的Java异常实现的缺陷
=======================

![分享一个你很可能不知道的Java异常实现的缺陷](https://img2023.cnblogs.com/blog/1755845/202212/1755845-20221206222653077-1634517621.png) Java中一个大家熟知的知识点就是异常捕获，try...catch...finally组合，但是很多人不知道这里面有一个关于Java的缺陷，或者说是异常实现的一点不足之处。

### 前言

> Java中一个大家熟知的知识点就是异常捕获，try...catch...finally组合，但是很多人不知道这里面有一个关于Java的缺陷，或者说是异常实现的一点不足之处。
> 
> 我这边就通过一个很简单的实验给大家演示下效果玩玩儿，希望大家能觉得有趣。

### 模拟

#### 1、自定义异常

> 这里，我们首先写一个自定义业务异常，专门用来抛出。

![在这里插入图片描述](https://img-blog.csdnimg.cn/a2626fa52d054a419d5e455fc94653dc.png#pic_center)

#### 2、模拟异常

> 然后，我们写个测试方法来捕获并抛出空指针异常。

![在这里插入图片描述](https://img-blog.csdnimg.cn/4fdd59aba0bb4df6a53123ba77c940ec.png#pic_center)

> 看下效果，OK没问题。

![在这里插入图片描述](https://img-blog.csdnimg.cn/6808db6d9cc640aabcba3ad029d17eb4.png#pic_center)

> 接下来，我们加上finally看看。

![在这里插入图片描述](https://img-blog.csdnimg.cn/14f5ec043b774c49b1420772b07b6832.png#pic_center)

> 看下效果，OK也没问题。

![在这里插入图片描述](https://img-blog.csdnimg.cn/03de375614534e398922a29f0c431d68.png#pic_center)

> 接下来我们这么做，在finally中抛出一个异常。

![在这里插入图片描述](https://img-blog.csdnimg.cn/8f1ca6c919664d5482ae8e23f07a4905.png#pic_center)

> 看下效果，发现catch的异常竟然被覆盖了。

![在这里插入图片描述](https://img-blog.csdnimg.cn/d2baf22fe6e14adda77df06049c5daf9.png#pic_center)

> 虽然这种场景很特殊，但这其实就是Java在异常实现上美中不足的地方，因为异常是作为程序出错的标志绝对不应忽略，可是这种场景下异常的的确确丢失了。

> 接下来，我们再测试一种情况，在finally中使用return，看看会发生什么。

![在这里插入图片描述](https://img-blog.csdnimg.cn/46bd4a9d850f41388196d7d76035901f.png#pic_center)

> 看看效果，发现catch中捕获的异常干脆直接没了，仿佛从没来过。

![在这里插入图片描述](https://img-blog.csdnimg.cn/0b0fb07a10d54f4cb128c0497e160466.png#pic_center)

> 最后，我们再演示一种你可能工作中干过或者见过的莫名其妙的事情。
> 
> 我们修改一下这个测试方法，看代码。

![在这里插入图片描述](https://img-blog.csdnimg.cn/c114efb3d3814cc1b0caa3153b39761c.png#pic_center)

> 简单描述一下，你调用其他类的一个查询方法，那个方法可能习惯性的try..catch..finally了，而finally中还做了一些末尾必须要执行的操作，这个业务逻辑处理可能有几十行，你很可能又习惯性的做了一些判断以及异常的抛出。
> 
> 别不相信，当一个项目进入中期甚至赶进度的时候，方法套方法，不少人已经在机械的茫然的写代码，也可能是在别人的基础上改代码，你很可能不会太仔细地一行一行去看那些代码里究竟有什么，恰巧测试的时候也没出什么大问题。

> 那么结果可能就是下面这样，你会发现自己一开始特意抛出的那个捕获该查询方法异常的玩意儿没一点效果，也不知道去哪儿了，怎么找也找不到，不知从哪儿冒出来下面这个莫名其妙的异常，后来想不到也就算了。

![在这里插入图片描述](https://img-blog.csdnimg.cn/813c418531b348fd8b03f2adb7b69ced.png#pic_center)

### 原因

> 这其实就是Java异常实现的一个不足，异常是程序出错的标志，怎么都不应该被忽略掉，更不用说是finally这种常用的行为，直接或间接地造成了异常的丢失。
> 
> 《Thinking In Java》的作者有明确指出这个异常，认为这是相当严重的缺陷，`是一个可能造成异常完全丢失的缺陷，而且是以一种更微妙、更难以察觉的方式在进行。`
> 
> 而C++就处理的很好，会将这种在第一个异常被处理之前抛出第二个异常的情况视为严重的编程错误。

### 总结

> 知道了这个缺陷后，其实就很好避免了。
> 
> 1、避免在finally中抛出异常；
> 
> 2、避免在finally中使用return；
> 
> 3、catch中一定要养成log.error记录异常日志的好习惯，因为log是一定会记录下来的，至少不会让你毫无线索。

> 结尾再演示下加了日志的效果，只要是catch我都加上日志，那么一定不会错过。

![在这里插入图片描述](https://img-blog.csdnimg.cn/07314bed30154aed934b30372a8d7abe.png#pic_center)

* * *

原创文章纯手打，一个一个字敲出来的，`键盘上全是血`，如果觉得有帮助麻烦点个`推荐`吧~

本人致力于分享工作中的经验及趣事，喜欢的话可以进主页`关注一下`哦~

喜欢就点一下推荐吧~~